apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rocketchats.open.rocket.chat
spec:
  group: open.rocket.chat
  names:
    kind: RocketChat
    listKind: RocketChatList
    plural: rocketchats
    singular: rocketchat
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
